# ServiceAccount: sm-legal-contract
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "sm-legal-contract.serviceAccountName" . }}
  labels:
    {{- include "sm-legal-contract.commonLabels" . | nindent 4 }}
automountServiceAccountToken: false
