"""add business tables

Revision ID: 0002_business_tables
Revises: 0001_initial
Create Date: 2026-09-23 20:09:36.680370
"""
from __future__ import annotations
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0002_business_tables'
down_revision: Union[str, None] = '0001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lc_contract_templates',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lc_contract_templates_code'), 'lc_contract_templates', ['code'], unique=True)
    op.create_index(op.f('ix_lc_contract_templates_status'), 'lc_contract_templates', ['status'], unique=False)
    op.create_table('lc_contracts',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('contract_no', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('party_a', sa.String(length=128), nullable=False),
    sa.Column('party_b', sa.String(length=128), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('sign_date', sa.Date(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lc_contracts_contract_no'), 'lc_contracts', ['contract_no'], unique=True)
    op.create_index(op.f('ix_lc_contracts_status'), 'lc_contracts', ['status'], unique=False)
    op.create_index(op.f('ix_lc_contracts_title'), 'lc_contracts', ['title'], unique=False)
    op.create_table('lc_contract_approvals',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('contract_id', sa.String(length=64), nullable=False),
    sa.Column('approver_id', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['lc_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lc_contract_approvals_contract_id'), 'lc_contract_approvals', ['contract_id'], unique=False)
    op.create_table('lc_contract_archives',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('contract_id', sa.String(length=64), nullable=False),
    sa.Column('file_ref', sa.String(length=256), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('archived_by', sa.String(length=64), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['lc_contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lc_contract_archives_contract_id'), 'lc_contract_archives', ['contract_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_lc_contract_archives_contract_id'), table_name='lc_contract_archives')
    op.drop_table('lc_contract_archives')
    op.drop_index(op.f('ix_lc_contract_approvals_contract_id'), table_name='lc_contract_approvals')
    op.drop_table('lc_contract_approvals')
    op.drop_index(op.f('ix_lc_contracts_title'), table_name='lc_contracts')
    op.drop_index(op.f('ix_lc_contracts_status'), table_name='lc_contracts')
    op.drop_index(op.f('ix_lc_contracts_contract_no'), table_name='lc_contracts')
    op.drop_table('lc_contracts')
    op.drop_index(op.f('ix_lc_contract_templates_status'), table_name='lc_contract_templates')
    op.drop_index(op.f('ix_lc_contract_templates_code'), table_name='lc_contract_templates')
    op.drop_table('lc_contract_templates')
    # ### end Alembic commands ###
